import { boards } from "./definitions/boards.js";
import { parts } from "./definitions/parts.js";
import { physical } from "./definitions/physical.js";
import { validateDefinition, type Definition, type Pin } from "./schema.js";
export type { Definition, Pin } from "./schema.js";
export const catalog: readonly Definition[] = [...boards, ...parts, ...physical].map(validateDefinition);
if (new Set(catalog.map(d => d.id)).size !== catalog.length) throw new Error("Duplicate component definition ID");
const definitions = new Map(catalog.map(d => [d.id, d]));
export const getDefinition = (id: unknown) => typeof id === "string" ? definitions.get(id) : undefined;
export const getPin = (definitionId: string, pinId: string): Pin | undefined => getDefinition(definitionId)?.pins.find(pin => pin.id === pinId);
