import { test, expect, type Page } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { protectPreview } from "./protectedPreview";
import type { KinetableProjectV4 } from "../src/projects/v4";
test.beforeEach(async ({context})=>protectPreview(context));
async function setup(page:Page){await page.goto("/home");await expect(page).toHaveURL(/\/start$/);await page.getByRole("radio",{name:"ESP32",exact:true}).check();await page.getByRole("button",{name:"Continue with ESP32"}).click();await expect(page).toHaveURL(/\/home$/);}
async function saved(page:Page):Promise<KinetableProjectV4>{const id=await page.locator("[data-project-id]").getAttribute("data-project-id");return page.evaluate(id=>new Promise((resolve,reject)=>{const r=indexedDB.open("kinetable");r.onerror=()=>reject(r.error);r.onsuccess=()=>{const q=r.result.transaction("projects").objectStore("projects").get(id!);q.onsuccess=()=>resolve(q.result.document);q.onerror=()=>reject(q.error);};}),id);}
test("first Home, real BONK, project retrieval, direct refresh and guidance",async({page})=>{
  await setup(page);await expect(page.getByText("No AI provider required.",{exact:false})).toBeVisible();await page.getByRole("button",{name:/Try BONK/}).click();
  await expect(page.locator("[data-project-id]")).toBeVisible();const id=(await saved(page)).id;expect((await saved(page)).logic).toHaveLength(2);
  await page.getByRole("button",{name:"Skip guidance"}).click();await page.reload();await expect(page.getByLabel("Workbench guidance")).toHaveCount(0);
  await page.goto("/projects");await page.getByRole("link",{name:/BONK circuit preview/}).click();await expect(page).toHaveURL(new RegExp(id));await page.reload();expect((await saved(page)).id).toBe(id);
  await page.goto("/table");await expect(page).toHaveURL(new RegExp(id));await page.goto("/projects/missing-project");await expect(page.getByRole("heading",{name:"This project isn’t here."})).toBeVisible();
  await page.getByRole("link",{name:"Go to Projects"}).click();await page.goto("/projects/new");await page.getByRole("button",{name:"Create project",exact:true}).click();await expect(page.locator("[data-project-id]")).toBeVisible();expect((await saved(page)).components).toHaveLength(1);expect((await saved(page)).id).not.toBe(id);
});
test("themes follow System, persist explicit choices and account keyboard focus",async({page})=>{
  await page.emulateMedia({colorScheme:"dark"});await page.goto("/settings/appearance");await expect(page.locator("html")).toHaveAttribute("data-theme","dark");
  await page.getByRole("button",{name:"Light",exact:true}).click();await expect(page.locator("html")).toHaveAttribute("data-theme","light");await page.reload();await expect(page.getByRole("button",{name:"Light",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.getByRole("button",{name:"System",exact:true}).click();await page.emulateMedia({colorScheme:"light"});await expect(page.locator("html")).toHaveAttribute("data-theme","light");
  await page.getByRole("button",{name:"Guest account"}).click();await expect(page.locator(".account-menu a").first()).toBeFocused();await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Guest account"})).toBeFocused();await expect(page.locator(".account-menu")).toHaveCount(0);
});
test("AI Logic previews two to three, applies shared commands, persists and survives a provider failure",async({page})=>{
  await setup(page);await page.getByRole("button",{name:/Try BONK/}).click();await expect(page.locator("[data-project-id]")).toBeVisible();
  await page.evaluate(()=>localStorage.setItem("kinetable:providers:v1",JSON.stringify({profile:{id:"default",name:"QA",routes:[{id:"qa",providerId:"custom",transport:"CUSTOM_OPENAI_COMPATIBLE",modelId:"qa",baseUrl:"https://example.com/v1",authMode:"none",credentialIds:[],priority:0,enabled:true}]},credentials:[]})));
  await page.route("**/api/ai/plan",async route=>{const body=route.request().postDataJSON();expect(body.task).toBe("logic");const rule=structuredClone(body.project.logic[0]);rule.do.find((a:{kind:string})=>a.kind==="buzzer").count=3;await route.fulfill({json:{status:"supported",summary:"Change two beeps to three",unsupportedReason:"",revision:body.input.revision,commands:[{type:"logic.rule.update",rule}]}});});
  await page.getByRole("button",{name:"Logic",exact:true}).click();await page.getByLabel("✦ Describe what should happen…").fill("Make the buzzer beep three times.");await page.getByRole("button",{name:"Preview behavior →"}).click();await expect(page.locator(".ai-change-preview del")).toContainText("2 times");await expect(page.locator(".ai-change-preview")).toContainText("3 times");expect((await saved(page)).logic[0].do[2]).toMatchObject({count:2});await page.getByRole("button",{name:"Apply",exact:true}).click();await expect.poll(async()=>(await saved(page)).logic[0].do[2]).toMatchObject({count:3});
  await page.reload();await page.getByRole("button",{name:"Logic",exact:true}).click();await expect(page.getByLabel("Action 3 beep count")).toHaveValue("3");
  const before=await saved(page);await page.unroute("**/api/ai/plan");await page.route("**/api/ai/plan",route=>route.fulfill({status:503,json:{code:"PROVIDER_UNAVAILABLE"}}));await page.getByLabel("✦ Describe what should happen…").fill("Beep four times");await page.getByRole("button",{name:"Preview behavior →"}).click();await expect(page.getByRole("alert")).toBeVisible();expect(await saved(page)).toEqual(before);
});
test("all product surfaces at five widths with rendered canvases and no overflow",async({page})=>{
  test.setTimeout(300000);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));mkdirSync("../../output/playwright/correction",{recursive:true});
  await setup(page);for(const [width,height] of [[390,844],[768,1024],[1440,900],[1600,1000],[1920,1080]]){await page.setViewportSize({width,height});await expect(page.locator(".home-hardware canvas")).toBeVisible();await page.waitForTimeout(250);await page.screenshot({path:`../../output/playwright/correction/first-home-${width}.png`,fullPage:true});} await page.getByRole("button",{name:/Try BONK/}).click();await expect(page.locator("[data-project-id]")).toBeVisible();const id=(await saved(page)).id;
  for(const [width,height] of [[390,844],[768,1024],[1440,900],[1600,1000],[1920,1080]]){
    await page.setViewportSize({width,height});
    for(const [name,url] of [["home","/home"],["projects","/projects"],["setup","/start"],["new","/projects/new"],["auth","/auth"],["settings-account","/settings/account"],["appearance","/settings/appearance"],["providers","/settings/providers"],["build",`/projects/${id}`]]){
      await page.goto(url);await expect(page.locator("#app-main")).toBeVisible();await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await page.locator("body *").evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,10).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right}))))).toBe(true);await page.screenshot({path:`../../output/playwright/correction/${name}-${width}.png`,fullPage:true});
    }
    await expect(page.locator(".workbench-surface canvas")).toBeVisible();
    if(await page.getByRole("button",{name:"Skip guidance"}).count())await page.getByRole("button",{name:"Skip guidance"}).click();
    await page.getByRole("button",{name:"Guest account"}).click();await page.screenshot({path:`../../output/playwright/correction/account-${width}.png`,fullPage:true});await page.keyboard.press("Escape");
    await page.getByText("Parts & wires",{exact:true}).click();await page.getByRole("button",{name:"ESP32 Dev Module",exact:true}).click();await page.waitForTimeout(250);await page.screenshot({path:`../../output/playwright/correction/inspector-${width}.png`,fullPage:true});await page.getByRole("button",{name:"Close inspector"}).click();
    await page.getByRole("button",{name:"Wire",exact:true}).click();await page.getByText("Connect pins",{exact:true}).click();await page.getByLabel("From part").selectOption("board-main");await page.getByLabel("From",{exact:true}).selectOption("pin:board-main:gpio23");await page.getByRole("button",{name:"Inspect from"}).click();await page.waitForTimeout(100);await page.screenshot({path:`../../output/playwright/correction/wiring-${width}.png`,fullPage:true});await page.keyboard.press("Escape");
    for(const mode of ["Logic","Simulate","Explain"]){await page.getByRole("button",{name:mode,exact:true}).click();await expect(page.locator(".workbench-gesture,.workbench-error")).toHaveCount(0);await page.waitForTimeout(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`../../output/playwright/correction/${mode.toLowerCase()}-${width}.png`,fullPage:true});}
  }
  await page.goto("/settings/appearance");await page.getByRole("button",{name:"Dark",exact:true}).click();for(const [name,url] of [["dark-home","/home"],["dark-build",`/projects/${id}`]]){await page.goto(url);await expect(page.locator("#app-main")).toBeVisible();await expect(page.locator("canvas")).toBeVisible();await page.waitForTimeout(300);await page.screenshot({path:`../../output/playwright/correction/${name}.png`,fullPage:true});}await page.getByRole("button",{name:"Logic",exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:"../../output/playwright/correction/dark-logic.png",fullPage:true});expect(errors).toEqual([]);
});

test("provider credentials stay masked and separate from project persistence",async({page})=>{
  await setup(page);await page.getByRole("button",{name:/Try BONK/}).click();await expect(page.locator("[data-project-id]")).toBeVisible();const before=await saved(page);
  await page.goto("/settings/providers");await page.getByLabel("Add provider").selectOption("openai");await page.getByRole("button",{name:"Add route"}).click();await page.locator(".settings-route > summary").click();
  const key="sk-qa-fictional-key-12345678";await page.getByLabel("Key label").fill("QA remembered");await page.getByLabel("API key",{exact:true}).fill(key);await page.getByLabel("Remember on this device").check();await page.getByRole("button",{name:"Add key",exact:true}).click();await expect(page.getByText("Key added.",{exact:true})).toBeVisible();await expect(page.getByLabel("API key",{exact:true})).toHaveValue("");
  expect(await page.evaluate(secret=>JSON.stringify(localStorage).includes(secret),key)).toBe(false);await page.reload();await page.locator(".settings-route > summary").click();await expect(page.locator(".settings-keys")).toContainText("remembered here");await expect(page.locator(".settings-keys")).toContainText("5678");await page.screenshot({path:"../../output/playwright/correction/providers-configured.png",fullPage:true});
  await page.goto(`/projects/${before.id}`);expect(await saved(page)).toEqual(before);expect(JSON.stringify(await saved(page))).not.toContain(key);
  await page.goto("/settings/providers");await page.locator(".settings-route > summary").click();await page.locator(".settings-keys .settings-row").first().getByRole("button",{name:"Remove",exact:true}).click();await expect(page.locator(".settings-keys")).not.toContainText("QA remembered");
});
