export type RemotePreset = { id: string; name: string; baseUrl: string; docs: string; protocol: "openai" | "anthropic"; models: boolean };
// Fixed origins only. Custom endpoints use the separately checked public HTTPS path.
export const remotePresets: readonly RemotePreset[] = [
  { id: "openai", name: "OpenAI", baseUrl: "https://api.openai.com/v1", docs: "https://platform.openai.com/docs/api-reference/chat/create", protocol: "openai", models: true },
  { id: "anthropic", name: "Anthropic", baseUrl: "https://api.anthropic.com/v1", docs: "https://docs.anthropic.com/en/api/messages", protocol: "anthropic", models: true },
  { id: "gemini", name: "Google Gemini", baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai", docs: "https://ai.google.dev/gemini-api/docs/openai", protocol: "openai", models: true },
  { id: "xai", name: "xAI", baseUrl: "https://api.x.ai/v1", docs: "https://docs.x.ai/developers/rest-api-reference/inference", protocol: "openai", models: true },
  { id: "groq", name: "Groq", baseUrl: "https://api.groq.com/openai/v1", docs: "https://console.groq.com/docs/openai", protocol: "openai", models: true },
  { id: "cerebras", name: "Cerebras", baseUrl: "https://api.cerebras.ai/v1", docs: "https://inference-docs.cerebras.ai/resources/openai", protocol: "openai", models: true },
  { id: "together", name: "Together AI", baseUrl: "https://api.together.xyz/v1", docs: "https://docs.together.ai/docs/inference-overview", protocol: "openai", models: true },
  { id: "fireworks", name: "Fireworks AI", baseUrl: "https://api.fireworks.ai/inference/v1", docs: "https://docs.fireworks.ai/guides/querying-text-models", protocol: "openai", models: true },
  { id: "mistral", name: "Mistral AI", baseUrl: "https://api.mistral.ai/v1", docs: "https://docs.mistral.ai/api/", protocol: "openai", models: true },
  { id: "deepseek", name: "DeepSeek", baseUrl: "https://api.deepseek.com/v1", docs: "https://api-docs.deepseek.com/", protocol: "openai", models: true },
  { id: "openrouter", name: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1", docs: "https://openrouter.ai/docs/api/reference/overview", protocol: "openai", models: true },
  { id: "cohere", name: "Cohere", baseUrl: "https://api.cohere.ai/compatibility/v1", docs: "https://docs.cohere.com/docs/compatibility-api", protocol: "openai", models: true },
  { id: "deepinfra", name: "DeepInfra", baseUrl: "https://api.deepinfra.com/v1/openai", docs: "https://docs.deepinfra.com/chat/overview", protocol: "openai", models: false },
  { id: "nvidia", name: "NVIDIA NIM", baseUrl: "https://integrate.api.nvidia.com/v1", docs: "https://docs.api.nvidia.com/nim/reference/llm-apis", protocol: "openai", models: false },
  { id: "huggingface", name: "Hugging Face Inference", baseUrl: "https://router.huggingface.co/v1", docs: "https://huggingface.co/docs/inference-providers/index", protocol: "openai", models: true },
  { id: "alibaba", name: "Alibaba Cloud / Qwen", baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", docs: "https://www.alibabacloud.com/help/en/model-studio/compatibility-of-openai-with-dashscope", protocol: "openai", models: false },
  { id: "moonshot", name: "Moonshot AI / Kimi", baseUrl: "https://api.moonshot.ai/v1", docs: "https://github.com/MoonshotAI/kimi-code/blob/main/docs/en/configuration/providers.md", protocol: "openai", models: false },
  { id: "zai", name: "Z.AI / GLM", baseUrl: "https://api.z.ai/api/paas/v4", docs: "https://zcode.z.ai/en/docs/configuration", protocol: "openai", models: false },
  { id: "minimax", name: "MiniMax", baseUrl: "https://api.minimax.io/v1", docs: "https://platform.minimax.io/docs/guides/text-generation", protocol: "openai", models: false },
  { id: "byteplus", name: "BytePlus ModelArk", baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3", docs: "https://docs.byteplus.com/zh-CN/docs/modelark/1330626", protocol: "openai", models: false },
  { id: "tencent", name: "Tencent Cloud TokenHub", baseUrl: "https://tokenhub-intl.tencentcloudmaas.com/v1", docs: "https://intl.cloud.tencent.com/ind/document/product/1300/80632", protocol: "openai", models: false },
  { id: "sambanova", name: "SambaNova", baseUrl: "https://api.sambanova.ai/v1", docs: "https://docs.sambanova.ai/docs/en/integrations/vscode", protocol: "openai", models: false },
  { id: "nebius", name: "Nebius Token Factory", baseUrl: "https://api.tokenfactory.nebius.com/v1", docs: "https://docs.tokenfactory.nebius.com/quickstart", protocol: "openai", models: false },
  { id: "baseten", name: "Baseten", baseUrl: "https://inference.baseten.co/v1", docs: "https://www.baseten.co/library/glm-4-7/", protocol: "openai", models: false },
  { id: "modal", name: "Modal Shared Endpoints", baseUrl: "https://inference.us-west.modal.direct/v1", docs: "https://modal.com/docs/guide/endpoint-integrations", protocol: "openai", models: true },
  { id: "digitalocean", name: "DigitalOcean Gradient", baseUrl: "https://inference.do-ai.run/v1", docs: "https://docs.digitalocean.com/products/inference/how-to/use-with-coding-agents/", protocol: "openai", models: false },
  { id: "friendli", name: "FriendliAI", baseUrl: "https://api.friendli.ai/serverless/v1", docs: "https://friendli.ai/models/zai-org/GLM-5.3", protocol: "openai", models: false },
  { id: "novita", name: "Novita AI", baseUrl: "https://api.novita.ai/openai/v1", docs: "https://docs.novita.ai/guides/llm-api", protocol: "openai", models: false },
  { id: "gmicloud", name: "GMICloud", baseUrl: "https://api.gmi-serving.com/v1", docs: "https://www.gmicloud.ai/en/developers", protocol: "openai", models: false },
  { id: "inference-net", name: "Inference.net", baseUrl: "https://api.inference.net/v1", docs: "https://docs.inference.net/api/api-quickstart", protocol: "openai", models: true },
  { id: "azure-openai", name: "Azure OpenAI", baseUrl: "", docs: "https://learn.microsoft.com/en-us/azure/foundry/openai/api-version-lifecycle", protocol: "openai", models: false },
  { id: "bedrock", name: "Amazon Bedrock API key", baseUrl: "", docs: "https://docs.aws.amazon.com/bedrock/latest/userguide/inference-chat-completions.html", protocol: "openai", models: false },
  { id: "cloudflare", name: "Cloudflare Workers AI", baseUrl: "", docs: "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/", protocol: "openai", models: false },
  { id: "vertex", name: "Google Vertex AI access token", baseUrl: "", docs: "https://cloud.google.com/vertex-ai/generative-ai/docs/start/openai", protocol: "openai", models: false },
];
export function remotePreset(id: string): RemotePreset | undefined { return remotePresets.find(p => p.id === id); }
