import type { Definition } from "../schema.js";
const accessed = "2026-09-28";
const asset = (id: string): Definition["asset"] => ({ kind: "procedural", id, license: "Kinetable original" });
export const parts: readonly Definition[] = [
  { id:"led-5mm", name:"LED", description:"A two-lead light-emitting diode. It needs a series resistor.", kind:"component", category:"output", aliases:["5 mm LED", "light emitting diode"], supportedVariant:"Generic two-lead 5 mm indicator LED; 220 Ω series resistor required", verification:"profiled", limitations:"Forward voltage, polarity markings and brightness vary by actual LED.", planning:"Connect cathode to board ground and anode through a 220 Ω series resistor to a board GPIO.", sources:[], visualId:"led", asset:asset("led"), electricalModel:"led-passive", pins:[{id:"anode",role:"passive"},{id:"cathode",role:"passive"}], simulation:"topology-dependent" },
  { id:"resistor-220r", name:"220 Ω resistor", description:"Limits current in a circuit path.", kind:"component", category:"passive", aliases:["220 ohm resistor", "220R"], supportedVariant:"Generic 220 Ω through-hole resistor", verification:"profiled", limitations:"Tolerance and power rating are not modeled; check the physical part before use.", sources:[], visualId:"resistor", asset:asset("resistor"), electricalModel:"resistor", pins:[{id:"a",role:"passive"},{id:"b",role:"passive"}], simulation:"topology-dependent" },
  { id:"push-button", name:"Push button", description:"A momentary switch with two modeled terminals.", kind:"component", category:"input", aliases:["momentary button", "tactile switch"], supportedVariant:"Generic normally-open two-terminal push button", verification:"profiled", limitations:"Four-leg switch internals are represented as two terminals; check physical pin pairs.", planning:"Connect one terminal to board GPIO and the other to ground; use input pull-up semantics.", sources:[], visualId:"button", asset:asset("button"), electricalModel:"momentary-switch", pins:[{id:"a",role:"passive"},{id:"b",role:"passive"}], simulation:"topology-dependent" },
  { id:"grove-buzzer-v1-1", name:"Grove Buzzer V1.1", description:"A buzzer module controlled by a digital signal.", kind:"component", category:"output", aliases:["Grove buzzer", "piezo buzzer"], supportedVariant:"Grove Buzzer V1.1 operated at 3.3 V in Kinetable", verification:"profiled", manufacturer:"Seeed Studio", model:"Grove Buzzer V1.1", limitations:"Seeed documents 3.3 V and 5 V operation; this supported profile conservatively uses 3.3 V signals and supply.", sources:[{title:"Grove - Buzzer",publisher:"Seeed Studio",type:"manufacturer",url:"https://wiki.seeedstudio.com/Grove-Buzzer/",accessed}], visualId:"buzzer", asset:asset("buzzer"), electricalModel:"buzzer", pins:[{id:"vcc",role:"power"},{id:"gnd",role:"ground"},{id:"sig",role:"digital-in"}], supply:3.3, signalMaxVolts:3.3, simulation:"topology-dependent" },
  { id:"hc-sr501", name:"HC-SR501 PIR", description:"A passive infrared motion sensor with a digital output.", kind:"component", category:"sensor", aliases:["motion sensor", "PIR"], supportedVariant:"Conservative HC-SR501 style module, USB powered board and 5 V VCC", verification:"profiled", limitations:"Clone supply, output high level, timings and sensitivity vary; confirm your board before physical wiring.", planning:"Use the board's 5 V rail when USB powered; connect OUT to a board GPIO.", sources:[{title:"PIR motion sensor HC-SR501",publisher:"Addicore",type:"vendor",url:"https://www.addicore.com/products/pir-infrared-motion-sensor-hc-sr501",accessed}], visualId:"pir", asset:asset("pir"), electricalModel:"pir", pins:[{id:"vcc",role:"power"},{id:"gnd",role:"ground"},{id:"out",role:"digital-out"}], supply:5, simulation:"topology-dependent" },
  { id:"oled-ssd1306-i2c-3v3", name:"3.3 V SSD1306 I²C OLED", description:"A small display connected over I²C.", kind:"component", category:"output", aliases:["OLED", "SSD1306 display"], supportedVariant:"Generic 3.3 V four-pin I²C module; no built-in level shifting assumed", verification:"profiled", limitations:"The SSD1306 controller datasheet does not verify any particular breakout's regulator or pull-ups.", planning:"Connect SDA and SCL to the selected board's modeled I²C pins.", sources:[{title:"SSD1306 controller datasheet",publisher:"Solomon Systech",type:"datasheet",url:"https://docs.sparkfun.com/SparkFun_Qwiic_OLED_1.3in/assets/board_files/SSD1306.pdf",accessed}], visualId:"oled", asset:asset("oled"), electricalModel:"ssd1306-i2c", pins:[{id:"vcc",role:"power"},{id:"gnd",role:"ground"},{id:"sda",role:"i2c-sda"},{id:"scl",role:"i2c-scl"}], supply:3.3, signalMaxVolts:3.3, simulation:"topology-dependent" },
  { id:"dht11-module", name:"DHT11 module", description:"A temperature and humidity module with a digital data pin.", kind:"component", category:"sensor", aliases:["DHT11", "temperature sensor", "humidity sensor"], supportedVariant:"DHT11 sensor module operated at 3.3 V", verification:"profiled", limitations:"Module PCB and pull-up resistor vary; the sensor datasheet alone does not verify a generic module.", sources:[{title:"DHT11 technical data sheet",publisher:"Aosong",type:"datasheet",url:"https://akizukidenshi.com/goodsaffix/DHT11_20180119.pdf",accessed}], visualId:"dht11", asset:asset("dht11"), electricalModel:"dht11", pins:[{id:"vcc",role:"power"},{id:"gnd",role:"ground"},{id:"data",role:"digital-out"}], supply:3.3, simulation:"topology-dependent" },
];
